### ISSUE TITLE
Control skins stopped working.

### ISSUE THREAD

**Issue by szroman** [pradosoft/prado#814]
Defining skins for selected theme does not affect controls.

**Comment by ctrlaltca** [comment]
Thank you, fixed in master

**Comment by szroman** [comment]
Thank you for your quick response. Still doesn't work in my application. Replacing framework/Web/UI/TTemplate.php is all I have to do, to make it work?

**Comment by ctrlaltca** [comment]
try to clean the application cache: delete the protected/runtime/application-4.2.1 directory

**Comment by szroman** [comment]
thank you, it works
